name: 'GitHub Actions rainpat daily check in'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 4 * * *'

jobs:
  daily_check_in:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: 'Install requirements'
        run: pip install -r ./rainpat_dci/requirements.txt
      - name: 'Working'
        run: python rainpat_dci/main.py
     
